import type { Locale } from '@/i18n'

const en = {
  notifications: 'Notifications',
  loading: 'Loading questions…',
  previous: 'Previous',
  resume: 'Continue with saved answer',
  title: 'Questions',
  open: 'Open',
  all: 'All',
  search: 'Search questions',
  empty: 'No questions here',
  refresh: 'Refresh',
  failed: 'Questions unavailable',
  answer: 'Answer and continue',
  discard: 'Discard question',
  dismissed: 'Discarded',
  other: 'Other answer',
  hard: 'User required',
  soft: 'Soft question',
  session: 'Open session',
  automatic: 'Automatic answer',
  user: 'Your answer',
  settings: 'Question settings',
  expiry: 'Wait limit in seconds, 0 means never expire',
  softTimeout: 'Soft review delay in seconds, 0 disables',
  budget: 'Review budget in seconds',
  save: 'Save',
  help: 'Questions stay saved after the wait ends. Soft questions get one read-only review using markdown memory and Hindsight. Missing evidence leaves them open. Hard questions never receive automatic answers. Only independent, already authorized work may continue.',
  more: 'Load more',
  deferred: 'Still open in Questions',
  scope: 'Current backend and profile',
  disconnected: 'Connect to a backend to view its questions.',
  savedOnly: 'Answer saved, but the session could not continue. Open the session to continue manually.'
}

export const questionCopy: Record<Locale, typeof en> = {
  en,
  ja: {
    notifications: '通知',
    loading: '質問を読み込み中…',
    previous: '前へ',
    resume: '保存した回答で続行',
    title: '質問',
    open: '未回答',
    all: 'すべて',
    search: '質問を検索',
    empty: '質問はありません',
    refresh: '更新',
    failed: '質問を取得できません',
    answer: '回答して続行',
    discard: '質問を破棄',
    dismissed: '破棄済み',
    other: 'その他の回答',
    hard: 'ユーザーの回答が必要',
    soft: '自動判断可能な質問',
    session: 'セッションを開く',
    automatic: '自動回答',
    user: 'あなたの回答',
    settings: '質問の設定',
    expiry: '待機上限の秒数、0は無期限',
    softTimeout: 'レビュー開始までの秒数、0は無効',
    budget: 'レビュー上限の秒数',
    save: '保存',
    more: 'さらに表示',
    deferred: '質問一覧で回答待ち',
    scope: '現在のバックエンドとプロファイル',
    disconnected: '質問を表示するにはバックエンドに接続してください。',
    savedOnly: '回答は保存されましたが、続行できませんでした。セッションを開いて手動で続行してください。',
    help: '待機終了後も質問を保存します。自動判断可能な質問はMarkdownメモリとHindsightで一度だけ確認します。根拠が不足する場合は未回答のままです。必須の質問には自動回答しません。既に許可された独立した作業のみ続行できます。'
  },
  zh: {
    notifications: '通知',
    loading: '正在加载问题…',
    previous: '上一页',
    resume: '使用已保存的回答继续',
    title: '问题',
    open: '待回答',
    all: '全部',
    search: '搜索问题',
    empty: '暂无问题',
    refresh: '刷新',
    failed: '无法获取问题',
    answer: '回答并继续',
    discard: '丢弃问题',
    dismissed: '已丢弃',
    other: '其他回答',
    hard: '必须由用户回答',
    soft: '可自动判断的问题',
    session: '打开会话',
    automatic: '自动回答',
    user: '你的回答',
    settings: '问题设置',
    expiry: '等待上限秒数，0表示永不过期',
    softTimeout: '自动审核延迟秒数，0表示禁用',
    budget: '审核上限秒数',
    save: '保存',
    more: '加载更多',
    deferred: '仍在问题列表中等待回答',
    scope: '当前后端和配置',
    disconnected: '连接后端以查看问题。',
    savedOnly: '回答已保存，但会话无法继续。请打开会话手动继续。',
    help: '等待结束后问题仍会保存。可自动判断的问题将通过Markdown记忆和Hindsight进行一次只读审核。证据不足时保持待回答。必须由用户回答的问题不会自动回答。只能继续已授权且独立的工作。'
  },
  'zh-hant': {
    notifications: '通知',
    loading: '正在載入問題…',
    previous: '上一頁',
    resume: '使用已儲存的回答繼續',
    title: '問題',
    open: '待回答',
    all: '全部',
    search: '搜尋問題',
    empty: '暫無問題',
    refresh: '重新整理',
    failed: '無法取得問題',
    answer: '回答並繼續',
    discard: '捨棄問題',
    dismissed: '已捨棄',
    other: '其他回答',
    hard: '必須由使用者回答',
    soft: '可自動判斷的問題',
    session: '開啟對話',
    automatic: '自動回答',
    user: '你的回答',
    settings: '問題設定',
    expiry: '等待上限秒數，0表示永不過期',
    softTimeout: '自動審核延遲秒數，0表示停用',
    budget: '審核上限秒數',
    save: '儲存',
    more: '載入更多',
    deferred: '仍在問題清單中等待回答',
    scope: '目前後端與設定檔',
    disconnected: '連接後端以查看問題。',
    savedOnly: '回答已儲存，但對話無法繼續。請開啟對話手動繼續。',
    help: '等待結束後問題仍會儲存。可自動判斷的問題將透過Markdown記憶和Hindsight進行一次唯讀審核。證據不足時保持待回答。必須由使用者回答的問題不會自動回答。只能繼續已授權且獨立的工作。'
  },
  ar: {
    notifications: 'الإشعارات',
    loading: 'جارٍ تحميل الأسئلة…',
    previous: 'السابق',
    resume: 'المتابعة بالإجابة المحفوظة',
    title: 'الأسئلة',
    open: 'مفتوحة',
    all: 'الكل',
    search: 'البحث في الأسئلة',
    empty: 'لا توجد أسئلة',
    refresh: 'تحديث',
    failed: 'الأسئلة غير متاحة',
    answer: 'الإجابة والمتابعة',
    discard: 'تجاهل السؤال',
    dismissed: 'تم التجاهل',
    other: 'إجابة أخرى',
    hard: 'تتطلب المستخدم',
    soft: 'سؤال قابل للمراجعة',
    session: 'فتح الجلسة',
    automatic: 'إجابة تلقائية',
    user: 'إجابتك',
    settings: 'إعدادات الأسئلة',
    expiry: 'حد الانتظار بالثواني، 0 يعني بلا انتهاء',
    softTimeout: 'تأخير المراجعة بالثواني، 0 للتعطيل',
    budget: 'مدة المراجعة بالثواني',
    save: 'حفظ',
    more: 'تحميل المزيد',
    deferred: 'لا يزال مفتوحاً في الأسئلة',
    scope: 'الخادم والملف الحاليان',
    disconnected: 'اتصل بالخادم لعرض أسئلته.',
    savedOnly: 'تم حفظ الإجابة لكن تعذرت المتابعة. افتح الجلسة للمتابعة يدوياً.',
    help: 'تبقى الأسئلة محفوظة بعد انتهاء الانتظار. تحصل الأسئلة البسيطة على مراجعة واحدة للقراءة فقط باستخدام ذاكرة Markdown وHindsight. نقص الأدلة يتركها مفتوحة. الأسئلة الإلزامية لا تُجاب تلقائياً. يمكن فقط متابعة العمل المستقل والمصرح به مسبقاً.'
  }
}
